export const PRODUCT_LIST = 'product@ATTR_LIST' 
export const PRODUCT_PAGE_START = 'product@ATTR_PAGE_START' 
export const PRODUCT_PAGE_END = 'product@ATTR_PAGE_END' 
export const PRODUCT_LEVE_CATEGORIES = 'product@ATTR_LEVE_CATEGORIES' 
export const PRODUCT_ALL_ATTRS = 'product@ATTR_ALL_ATTRS' 
export const PRODUCT_COVER_IMAGE = 'product@PRODUCT_COVER_IMAGE' 
export const PRODUCT_MAIN_IMAGE = 'product@PRODUCT_MAIN_IMAGE' 
